### ISSUE TITLE
French keyboard has "z" twice but no "w"

### ISSUE THREAD

**Issue by GlueJuhaR** [vuplex/unity-keyboard#1]
As per title. In the French localized keyboard, the top row starts "a z e..." and the bottom row starts "z x c...", and "w" is completely omitted. The same applies to both upper and lower case.

Discovered in a native app using Vuplex, and confirmed in the online version at 

https://keyboard.vuplex.com/

**Comment by BinaryNate** [comment]
Thanks, Juha! I just fixed this issue in [this commit](https://github.com/vuplex/unity-keyboard/commit/c9d0089b51dacb717f21d27e98f98ba5c9a1f4f0) and I'll include this fix in the next release of 3D WebView. I also attached the updated version of KeyboardUi.cs.

[KeyboardUi.cs.zip](https://github.com/vuplex/unity-keyboard/files/4778076/KeyboardUi.cs.zip)
