### ISSUE TITLE
About Browser Features

### ISSUE THREAD

**Issue by wei-kris** [vuplex/unity-keyboard#4]
https://github.com/vuplex/unity-keyboard/blob/master/demo.gif

Hi, I see that this gif shows some browser functions: address bar, tab, voice, etc. Are these functions included in the asset?

**Comment by binarynate** [comment]
Hi @wei-kris 👋🏻. Thank you for your interest! No, 3D WebView doesn't yet have a browser window prefab with an address bar and tabs, but I have a feature request for that and plan to add that in the future. The address bar UI shown in the gif is from an app I created called [VR Browser](https://play.google.com/store/apps/details?id=design.sonic.vrdesktop), which I ultimately turned into the 3D WebView asset. For general questions in the future, please contact me through [the Vuplex contact page](https://support.vuplex.com/contact). If you'd like me to add you to the waitlist for the browser window prefab (with address bar UI), please send me your email address through that contact form.
