### ISSUE TITLE
Keyboard suspension

### ISSUE THREAD

**Issue by Karim-Sheetos2269** [vuplex/unity-keyboard#5]
I integrate the 3D WebView package for Android with VRIF Package in unity, but I am facing a big problem , As described in the video.
thank you

https://drive.google.com/file/d/1v6kGTc-nns2dWpL7x2rJ30BsaX4BdhbF/view?usp=share_link

**Comment by binarynate** [comment]
Hi, Ahmed 👋🏻. I answered the message you sent through the Vuplex support page, so please check your email inbox for my reply. A note for others that see this: please send support messages through the [support form](https://vuplex.com/contact).

**Comment by Karim-Sheetos2269** [comment]
Hi, thanks a lot for your reply, i will check again 🙏
